server:
  port: 15000
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


  rabbitmq:
    host: 192.168.170.130
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirm-type: correlated   #发送端确认的方式：关联方式，错误的消息，必须通知publisher
    publisher-returns: true   #发送返回true，服务器只要收到消息了就通知发送方。
    listener:
      type: simple
      simple:
        acknowledge-mode: manual  #手动确认


app:
  threadpool:
    core-pool-size: 4
    maximum-pool-size: 8
    work-queue-size: 200
    keep-alive-time: 60
  alipay:
    app-id: 2021000121623197
    merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCx3RDrEhh1pJEatJ6/lNPIz6CvjE6qIJZTgSVJkJKqtjgg0n98uKzJlZY1mDzK//Id5sX4n+h0UiH6t2X6ZX4m77T6FTcj9Z3Ix4y3KB7uZ24Z4PeFtDjpqjiEw58ekpIeA28OtkUMzWoyfacm4nMNt66wbhhBdmuTX0+Zzr99xBWCgUOf8AeipFxzJv1bh1EnlJXDqI4vkB26kJpm6g+FH8b/tQAcFOkxS5AWEs0pijfA9SgG6w175VdTdQsujGYuxiHDrvvgiGjxCtMz5KxWxIevSxRVzI0GP9ZgC1TUxnlwlMC/rx1AEkPsBdhxwoJbkmzGYvKSPrTdokaVD07LAgMBAAECggEBAJy/w7I3X2EGaG8NsT4MDl1SRj2PvKAIWhM7pL3hcLCMKIkcmggzxOtfLmMLSMBqslkR0XUckEM7QwDu8iurmHL+HBOt8Mt7IdQZsPSVojTe6FRcRCgMPYAIaQjwUeIisC1NP2nKzq3KtoXK4S3OsjDrqUOJs0y17XaSr9dQMsjFNrjeNvGDVcXmVvRTQgnDKvlAUfdZ3bJS+neU3cxHwMOD8RbYr5gfzzTrqENbWq7M17EB0SInKk08UiVXA5RHxINT3yugSZhG+W8lLDXgzltxKTsfBEEoQd4dwwFOjDP5EsoA1I33ThTF5pY3VIfc29MGxLT/mX4Zlo4FfgGb2lECgYEA4UokmT5RgZPLREVNfVJ3QynDArZlQdawB9PY7jvlMLwqcreKEJ5o0bj5Oxy/aDR+GYzPgBCTRATmWgVN8EudB+pesxcjRkC6j8iDt3SsmmsN28DyMKYq36msBf0Zj1plCrm4OlhM7UtDOZVIKwA0eVVimgGCXWDrDviHfDPCqbMCgYEAyhvpMchI6m2F1mwLKKIvyF22JoJV7D1JClf1XEhs4UCsXq5hBq+xsDOaVJaXlgpfoD7XEvkTjHlGpVMKey7ETMSPRu1CuaaXijDYOTaMCkKyRrHSfDUUMQ3p2Hvvofs7i7J6wOPIakbnsi7b4FbsZ/T/+iWu466rUBYL7b/4iokCgYEAvGsA/vVCv6d22gtICqccvZxAz5TyTMUcBf/kryKCxWap7bWZD9sceUJFl22sm59DU2UT6dxy/fFHIkTLcUwb8hHOz+NrCgd6wGQH3TgEX0VnmsHdDFj9BIBoMb4DUYRde0HmVU2iUNegSpmSePw75rpFs93NRQGYtbWfwn2bsccCgYAkZvqNeOGJN8jPYg5wdyXcFOTl8ru/HRq2vjj3MiRKPffN5eKb7bE3Z1P4wFb1M1Ed77OVOz+GIaHTzS0qGrZIjW6w+7L09Uh+H2YSh/yZLIInsYeTz4ufej4QO+Jhbnq/Ippxe5Vxbuv0b/QyZ/WUk9A3IepqH9/DQPVNETKW4QKBgDZa+8Mzb9HMYcWgQvxOJ03XNz3DLUS5DujzdW84GfyTTB801o097EMhLMcAKkmxfLBwsSftiCSQzp8lwIS+XLUTNgvL2EJertJ1YDeWai/t4KbkykE8PMg4y0B3OWYZOVTi6eXKYc9E1ITH/8pUS3wWgQzrogOWxyV+ATZkOepB
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoYIhYd9+hJrKGD6F+EyrrNeIIEr+5lC1cexGJC5cSpK8p3knOTvWbhmaL8ZBInuerlSIu8vTIAix+GC4r1Iv/LT3xLa/T1iRbPqbG3TMxmdJdefQZCtZDk1A2Q+Ty5qQ6caMYgno0W/ikx0MVUJPcKv52XhMElES2JRrDZqivrbUhzXJG3L7QW1a36onykuXKxfFeQP970kgKezAheHJt4ZBbjgz8BLYDAYGU9je+hdHMDvysEtNkn6Xds8oVFo8HF5p6RsCRnAD6SYfM2XtaZLDPlzGbDNXqrAHXTgBvwT7Qug2C7eBtrC6x2VWpEyQxgN/nzvNA/IhR4pRe8oE3QIDAQAB
    notify-url: http://69d525.natappfree.cc/rpcapi/payment/notify/success  #内网穿透  aaa.cccc.bbb/payment/notify
    return-url: http://payment.gmall.com/api/payment/alipay/success
    sign-type: RSA2
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do


