server:
  port: 80
spring:
  cloud:
    sentinel:
      enabled: true
    gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"  #允许所有来源访问
              allowedMethods: "*"  #允许所有请求方式跨域访问
              allowedHeaders: "*"
        routes:
          - id: product_route
            uri: lb://service-product
            predicates:
              - Path=/admin/product/**

          - id: front_route    #所有 域名的请求都来到 web-front 前端
            uri: lb://web-front
            predicates:
              - Host=**.gmall.com

