server:
  port: 80
spring:
  cloud:
    sentinel:
      enabled: true
    gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"  #允许所有来源访问
              allowedMethods: "*"  #允许所有请求方式跨域访问
              allowedHeaders: "*"
        routes:
          - id: product_route
            uri: lb://service-product
            predicates:
              - Path=/admin/product/**

          - id: user_route
            uri: lb://service-user
            predicates:
              - Path=/api/user/**

          - id: front_route    #所有 域名的请求都来到 web-front 前端
            uri: lb://web-front
            predicates:
              - Host=**.gmall.com

app:
  auth:
    login-page: http://passport.gmall.com/login.html
    login-url:
      - /order/**
    no-auth-url:
      - /rpc/inner/**   #内部的rpc请求浏览器不能直接访问